In [65]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [66]:
pwd = os.getcwd()
file_path = os.path.join(pwd, os.pardir, 'data/Week1_challenge_data_source(CSV).csv');

In [67]:
data = pd.read_csv(file_path, na_values=["undefined"], keep_default_na=True, parse_dates=["Start", "End"])

In [68]:
data.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,2019-04-04 12:01:00,770.0,2019-04-25 14:35:00,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,2019-04-09 13:04:00,235.0,2019-04-25 08:15:00,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,2019-04-09 17:42:00,1.0,2019-04-25 11:58:00,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,2019-04-10 00:31:00,486.0,2019-04-25 07:36:00,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,2019-04-12 20:10:00,565.0,2019-04-25 10:40:00,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [69]:
data.isna().sum()

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                          9559
Handset Type                                  9559
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

## Cleaning 
---

- remove duplicates
- fill missing values
- remove irrelevant missing values
- change to appropriate datatypes

In [70]:
clean_data = data.copy()

In [71]:
clean_data.shape

(150001, 55)

In [72]:
def missing_percentage(df):
    for column in df.columns:
        pct_missing = np.mean(df[column].isnull())
        print('{} - {}%'.format(column, round(pct_missing*100)))

In [73]:
missing_percentage(clean_data)

Bearer Id - 1%
Start - 0%
Start ms - 0%
End - 0%
End ms - 0%
Dur. (ms) - 0%
IMSI - 0%
MSISDN/Number - 1%
IMEI - 0%
Last Location Name - 1%
Avg RTT DL (ms) - 19%
Avg RTT UL (ms) - 19%
Avg Bearer TP DL (kbps) - 0%
Avg Bearer TP UL (kbps) - 0%
TCP DL Retrans. Vol (Bytes) - 59%
TCP UL Retrans. Vol (Bytes) - 64%
DL TP < 50 Kbps (%) - 1%
50 Kbps < DL TP < 250 Kbps (%) - 1%
250 Kbps < DL TP < 1 Mbps (%) - 1%
DL TP > 1 Mbps (%) - 1%
UL TP < 10 Kbps (%) - 1%
10 Kbps < UL TP < 50 Kbps (%) - 1%
50 Kbps < UL TP < 300 Kbps (%) - 1%
UL TP > 300 Kbps (%) - 1%
HTTP DL (Bytes) - 54%
HTTP UL (Bytes) - 55%
Activity Duration DL (ms) - 0%
Activity Duration UL (ms) - 0%
Dur. (ms).1 - 0%
Handset Manufacturer - 6%
Handset Type - 6%
Nb of sec with 125000B < Vol DL - 65%
Nb of sec with 1250B < Vol UL < 6250B - 62%
Nb of sec with 31250B < Vol DL < 125000B - 62%
Nb of sec with 37500B < Vol UL - 87%
Nb of sec with 6250B < Vol DL < 31250B - 59%
Nb of sec with 6250B < Vol UL < 37500B - 75%
Nb of sec with Vol DL < 6250B - 1%
Nb of sec with Vol UL < 1250B - 1%
Social Media DL (Bytes) - 0%
Social Media UL (Bytes) - 0%
Google DL (Bytes) - 0%
Google UL (Bytes) - 0%
Email DL (Bytes) - 0%
Email UL (Bytes) - 0%
Youtube DL (Bytes) - 0%
Youtube UL (Bytes) - 0%
Netflix DL (Bytes) - 0%
Netflix UL (Bytes) - 0%
Gaming DL (Bytes) - 0%
Gaming UL (Bytes) - 0%
Other DL (Bytes) - 0%
Other UL (Bytes) - 0%
Total UL (Bytes) - 0%
Total DL (Bytes) - 0%

In [74]:
clean_data.dropna(subset=["Bearer Id"], inplace=True)

In [75]:
clean_data.dropna(subset=["MSISDN/Number"], inplace=True)

In [76]:
clean_data["Handset Type"] = clean_data["Handset Type"].fillna("Unknown")
clean_data["Handset Manufacturer"] = clean_data["Handset Manufacturer"].fillna("Unknown")
clean_data["Last Location Name"] = clean_data["Last Location Name"].fillna("Unknown")

In [77]:
clean_data.fillna(clean_data.mean(numeric_only=True).round(), inplace=True)

In [78]:
missing_percentage(clean_data)

Bearer Id - 0%
Start - 0%
Start ms - 0%
End - 0%
End ms - 0%
Dur. (ms) - 0%
IMSI - 0%
MSISDN/Number - 0%
IMEI - 0%
Last Location Name - 0%
Avg RTT DL (ms) - 0%
Avg RTT UL (ms) - 0%
Avg Bearer TP DL (kbps) - 0%
Avg Bearer TP UL (kbps) - 0%
TCP DL Retrans. Vol (Bytes) - 0%
TCP UL Retrans. Vol (Bytes) - 0%
DL TP < 50 Kbps (%) - 0%
50 Kbps < DL TP < 250 Kbps (%) - 0%
250 Kbps < DL TP < 1 Mbps (%) - 0%
DL TP > 1 Mbps (%) - 0%
UL TP < 10 Kbps (%) - 0%
10 Kbps < UL TP < 50 Kbps (%) - 0%
50 Kbps < UL TP < 300 Kbps (%) - 0%
UL TP > 300 Kbps (%) - 0%
HTTP DL (Bytes) - 0%
HTTP UL (Bytes) - 0%
Activity Duration DL (ms) - 0%
Activity Duration UL (ms) - 0%
Dur. (ms).1 - 0%
Handset Manufacturer - 0%
Handset Type - 0%
Nb of sec with 125000B < Vol DL - 0%
Nb of sec with 1250B < Vol UL < 6250B - 0%
Nb of sec with 31250B < Vol DL < 125000B - 0%
Nb of sec with 37500B < Vol UL - 0%
Nb of sec with 6250B < Vol DL < 31250B - 0%
Nb of sec with 6250B < Vol UL < 37500B - 0%
Nb of sec with Vol DL < 6250B - 0%
Nb of sec with Vol UL < 1250B - 0%
Social Media DL (Bytes) - 0%
Social Media UL (Bytes) - 0%
Google DL (Bytes) - 0%
Google UL (Bytes) - 0%
Email DL (Bytes) - 0%
Email UL (Bytes) - 0%
Youtube DL (Bytes) - 0%
Youtube UL (Bytes) - 0%
Netflix DL (Bytes) - 0%
Netflix UL (Bytes) - 0%
Gaming DL (Bytes) - 0%
Gaming UL (Bytes) - 0%
Other DL (Bytes) - 0%
Other UL (Bytes) - 0%
Total UL (Bytes) - 0%
Total DL (Bytes) - 0%

In [79]:
# change columns to string to avoid numerical calculations on them
clean_data[["IMSI", "MSISDN/Number", "IMEI", "Last Location Name"]] = clean_data[["IMSI", "MSISDN/Number", "IMEI", "Last Location Name"]].astype(str)

In [80]:
clean_data.shape

(148506, 55)

In [81]:
# fix column naming issue on dataset
clean_data.rename(columns={"Dur. (ms)": "Dur. (s)", "Dur. (ms).1": "Dur. (ms)"}, inplace=True)

In [82]:
clean_data.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (s),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,2019-04-04 12:01:00,770.0,2019-04-25 14:35:00,662.0,1823652.0,208201448079117.0,33664962239.0,35521209507511.0,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,2019-04-09 13:04:00,235.0,2019-04-25 08:15:00,606.0,1365104.0,208201909211140.0,33681854413.0,35794009006359.0,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,2019-04-09 17:42:00,1.0,2019-04-25 11:58:00,652.0,1361762.0,208200314458056.0,33760627129.0,35281510359387.0,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,2019-04-10 00:31:00,486.0,2019-04-25 07:36:00,171.0,1321509.0,208201402342131.0,33750343200.0,35356610164913.0,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,2019-04-12 20:10:00,565.0,2019-04-25 10:40:00,954.0,1089009.0,208201401415120.0,33699795932.0,35407009745539.0,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [83]:
# checking for entire row of duplicates
clean_data.duplicated().sum()

0

In [85]:
output_file_path = os.path.join(pwd, os.pardir, 'data/clean_data.csv')
clean_data.to_csv(output_file_path, index=False)